<?php defined('InShopNC') or exit('Access Invalid!'); return array (
  'data' => 
  array (
    1057 => 
    array (
      'gc_id' => '1057',
      'gc_name' => '建材',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '0',
      'commis_rate' => '0',
      'gc_sort' => '0',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1058 => 
    array (
      'gc_id' => '1058',
      'gc_name' => '家具',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '0',
      'commis_rate' => '0',
      'gc_sort' => '1',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1073 => 
    array (
      'gc_id' => '1073',
      'gc_name' => '家居饰品',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '0',
      'commis_rate' => '0',
      'gc_sort' => '2',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1060 => 
    array (
      'gc_id' => '1060',
      'gc_name' => '灯具灯饰',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '0',
      'commis_rate' => '0',
      'gc_sort' => '3',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    262 => 
    array (
      'gc_id' => '262',
      'gc_name' => '手机',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '257',
      'commis_rate' => '0',
      'gc_sort' => '255',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    263 => 
    array (
      'gc_id' => '263',
      'gc_name' => '对讲机',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '257',
      'commis_rate' => '0',
      'gc_sort' => '255',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1061 => 
    array (
      'gc_id' => '1061',
      'gc_name' => '墙地面',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1057',
      'commis_rate' => '0',
      'gc_sort' => '0',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1062 => 
    array (
      'gc_id' => '1062',
      'gc_name' => '厨房卫浴',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1057',
      'commis_rate' => '0',
      'gc_sort' => '1',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1063 => 
    array (
      'gc_id' => '1063',
      'gc_name' => '基础建材',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1057',
      'commis_rate' => '0',
      'gc_sort' => '2',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1064 => 
    array (
      'gc_id' => '1064',
      'gc_name' => '定制品',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1057',
      'commis_rate' => '0',
      'gc_sort' => '3',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1065 => 
    array (
      'gc_id' => '1065',
      'gc_name' => '门窗',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1057',
      'commis_rate' => '0',
      'gc_sort' => '4',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1066 => 
    array (
      'gc_id' => '1066',
      'gc_name' => '床',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1058',
      'commis_rate' => '0',
      'gc_sort' => '0',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1067 => 
    array (
      'gc_id' => '1067',
      'gc_name' => '床垫',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1058',
      'commis_rate' => '0',
      'gc_sort' => '1',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1068 => 
    array (
      'gc_id' => '1068',
      'gc_name' => '沙发',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1058',
      'commis_rate' => '0',
      'gc_sort' => '2',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1069 => 
    array (
      'gc_id' => '1069',
      'gc_name' => '柜体',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1058',
      'commis_rate' => '0',
      'gc_sort' => '3',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1070 => 
    array (
      'gc_id' => '1070',
      'gc_name' => '红木家具',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1058',
      'commis_rate' => '0',
      'gc_sort' => '4',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1071 => 
    array (
      'gc_id' => '1071',
      'gc_name' => '榻榻米',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1058',
      'commis_rate' => '0',
      'gc_sort' => '5',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1072 => 
    array (
      'gc_id' => '1072',
      'gc_name' => '椅类',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1058',
      'commis_rate' => '0',
      'gc_sort' => '6',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1074 => 
    array (
      'gc_id' => '1074',
      'gc_name' => '桌类',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1058',
      'commis_rate' => '0',
      'gc_sort' => '7',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1075 => 
    array (
      'gc_id' => '1075',
      'gc_name' => '架类',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1058',
      'commis_rate' => '0',
      'gc_sort' => '8',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1076 => 
    array (
      'gc_id' => '1076',
      'gc_name' => '镜类',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1058',
      'commis_rate' => '0',
      'gc_sort' => '9',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1077 => 
    array (
      'gc_id' => '1077',
      'gc_name' => '屏风',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1058',
      'commis_rate' => '0',
      'gc_sort' => '10',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1083 => 
    array (
      'gc_id' => '1083',
      'gc_name' => '吊灯',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1060',
      'commis_rate' => '0',
      'gc_sort' => '0',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1084 => 
    array (
      'gc_id' => '1084',
      'gc_name' => '吸顶灯',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1060',
      'commis_rate' => '0',
      'gc_sort' => '1',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1085 => 
    array (
      'gc_id' => '1085',
      'gc_name' => '台灯',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1060',
      'commis_rate' => '0',
      'gc_sort' => '2',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1086 => 
    array (
      'gc_id' => '1086',
      'gc_name' => '壁灯',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1060',
      'commis_rate' => '0',
      'gc_sort' => '3',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1087 => 
    array (
      'gc_id' => '1087',
      'gc_name' => '落地灯',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1060',
      'commis_rate' => '0',
      'gc_sort' => '4',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1088 => 
    array (
      'gc_id' => '1088',
      'gc_name' => '镜前灯',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1060',
      'commis_rate' => '0',
      'gc_sort' => '5',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1089 => 
    array (
      'gc_id' => '1089',
      'gc_name' => '家居照明',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1060',
      'commis_rate' => '0',
      'gc_sort' => '6',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1090 => 
    array (
      'gc_id' => '1090',
      'gc_name' => '光源',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1060',
      'commis_rate' => '0',
      'gc_sort' => '7',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1094 => 
    array (
      'gc_id' => '1094',
      'gc_name' => '地砖',
      'type_id' => '43',
      'type_name' => '1号地砖',
      'gc_parent_id' => '1061',
      'commis_rate' => '1',
      'gc_sort' => '0',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1095 => 
    array (
      'gc_id' => '1095',
      'gc_name' => '墙砖',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1061',
      'commis_rate' => '1',
      'gc_sort' => '0',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1096 => 
    array (
      'gc_id' => '1096',
      'gc_name' => '壁纸',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1061',
      'commis_rate' => '1',
      'gc_sort' => '0',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1097 => 
    array (
      'gc_id' => '1097',
      'gc_name' => '实木复合地板',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1061',
      'commis_rate' => '1',
      'gc_sort' => '0',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1098 => 
    array (
      'gc_id' => '1098',
      'gc_name' => '软木地板',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1061',
      'commis_rate' => '1',
      'gc_sort' => '0',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1099 => 
    array (
      'gc_id' => '1099',
      'gc_name' => '石材',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1061',
      'commis_rate' => '1',
      'gc_sort' => '0',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1100 => 
    array (
      'gc_id' => '1100',
      'gc_name' => '地板辅料',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1061',
      'commis_rate' => '1',
      'gc_sort' => '0',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1101 => 
    array (
      'gc_id' => '1101',
      'gc_name' => 'gg',
      'type_id' => '43',
      'type_name' => '壁纸',
      'gc_parent_id' => '1061',
      'commis_rate' => '1',
      'gc_sort' => '0',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1078 => 
    array (
      'gc_id' => '1078',
      'gc_name' => '家纺',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1073',
      'commis_rate' => '0',
      'gc_sort' => '0',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1079 => 
    array (
      'gc_id' => '1079',
      'gc_name' => '家居用品',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1073',
      'commis_rate' => '0',
      'gc_sort' => '1',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1080 => 
    array (
      'gc_id' => '1080',
      'gc_name' => '餐厨用具',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1073',
      'commis_rate' => '0',
      'gc_sort' => '2',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1081 => 
    array (
      'gc_id' => '1081',
      'gc_name' => '布艺软饰',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1073',
      'commis_rate' => '0',
      'gc_sort' => '3',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
    1082 => 
    array (
      'gc_id' => '1082',
      'gc_name' => '智能家居',
      'type_id' => '0',
      'type_name' => '',
      'gc_parent_id' => '1073',
      'commis_rate' => '0',
      'gc_sort' => '4',
      'gc_virtual' => '0',
      'gc_title' => '',
      'gc_keywords' => '',
      'gc_description' => '',
      'gc_show' => '1',
    ),
  ),
  'parent' => 
  array (
    1057 => '0',
    1058 => '0',
    1073 => '0',
    1060 => '0',
    262 => '257',
    263 => '257',
    1061 => '1057',
    1062 => '1057',
    1063 => '1057',
    1064 => '1057',
    1065 => '1057',
    1066 => '1058',
    1067 => '1058',
    1068 => '1058',
    1069 => '1058',
    1070 => '1058',
    1071 => '1058',
    1072 => '1058',
    1074 => '1058',
    1075 => '1058',
    1076 => '1058',
    1077 => '1058',
    1083 => '1060',
    1084 => '1060',
    1085 => '1060',
    1086 => '1060',
    1087 => '1060',
    1088 => '1060',
    1089 => '1060',
    1090 => '1060',
    1094 => '1061',
    1095 => '1061',
    1096 => '1061',
    1097 => '1061',
    1098 => '1061',
    1099 => '1061',
    1100 => '1061',
    1101 => '1061',
    1078 => '1073',
    1079 => '1073',
    1080 => '1073',
    1081 => '1073',
    1082 => '1073',
  ),
  'children' => 
  array (
    0 => 
    array (
      0 => '1057',
      1 => '1058',
      2 => '1073',
      3 => '1060',
    ),
    257 => 
    array (
      0 => '262',
      1 => '263',
    ),
    1057 => 
    array (
      0 => '1061',
      1 => '1062',
      2 => '1063',
      3 => '1064',
      4 => '1065',
    ),
    1058 => 
    array (
      0 => '1066',
      1 => '1067',
      2 => '1068',
      3 => '1069',
      4 => '1070',
      5 => '1071',
      6 => '1072',
      7 => '1074',
      8 => '1075',
      9 => '1076',
      10 => '1077',
    ),
    1060 => 
    array (
      0 => '1083',
      1 => '1084',
      2 => '1085',
      3 => '1086',
      4 => '1087',
      5 => '1088',
      6 => '1089',
      7 => '1090',
    ),
    1061 => 
    array (
      0 => '1094',
      1 => '1095',
      2 => '1096',
      3 => '1097',
      4 => '1098',
      5 => '1099',
      6 => '1100',
      7 => '1101',
    ),
    1073 => 
    array (
      0 => '1078',
      1 => '1079',
      2 => '1080',
      3 => '1081',
      4 => '1082',
    ),
  ),
  'children2' => 
  array (
    1057 => 
    array (
      0 => '1094',
      1 => '1095',
      2 => '1096',
      3 => '1097',
      4 => '1098',
      5 => '1099',
      6 => '1100',
      7 => '1101',
    ),
  ),
);